baseURL = '/'
languageCode = 'en-us'
title = 'The SF Nexus'
theme = "gohugo-theme-ananke"
canonifyURLS=true
[menu]
[[menu.main]]
  name = 'About'
  pageRef = '/About'
  weight = 1
[[menu.main]]
  name = 'People'
  pageRef = '/People'
  weight = 2
[[menu.main]]
  name = 'Data'
  pageRef = '/Data'
  weight = 3
 [[menu.main]]
  name = 'OCR'
  pageRef = '/OCR'
  weight = 4
[[menu.main]]
  name = 'Models'
  pageRef = '/Models'
  weight = 5
